package com.ninepvi.shield;

/* This class is generated by JADX */
public final class R {

    public static final class drawable {
        public static final int alert_dialog_icon = 2130837504;
        public static final int btn_handle_nor = 2130837505;
        public static final int btn_handle_sel = 2130837506;
        public static final int btn_handle_selector = 2130837507;
        public static final int btn_nor = 2130837508;
        public static final int btn_sel = 2130837509;
        public static final int btn_selector = 2130837510;
        public static final int icon = 2130837511;
        public static final int img_result = 2130837512;
        public static final int logo = 2130837513;
        public static final int tab_assign_app_nor = 2130837514;
        public static final int tab_assign_app_sel = 2130837515;
        public static final int tab_install_app_nor = 2130837516;
        public static final int tab_install_app_sel = 2130837517;
        public static final int tab_scan_result_nor = 2130837518;
        public static final int tab_scan_result_sel = 2130837519;
        public static final int tab_trust_app_nor = 2130837520;
        public static final int tab_trust_app_sel = 2130837521;
    }

    public static final class layout {
        public static final int file_row = 2130903040;
        public static final int foot = 2130903041;
        public static final int list_content = 2130903042;
        public static final int list_content_main = 2130903043;
        public static final int main = 2130903044;
    }

    public static final class string {
        public static final int app_name = 2130968576;
        public static final int username = 2130968577;
        public static final int password = 2130968578;
        public static final int login = 2130968579;
        public static final int reset = 2130968580;
        public static final int blogname = 2130968581;
        public static final int blogweb = 2130968582;
        public static final int s_install = 2130968583;
        public static final int s_appoint = 2130968584;
        public static final int s_trust = 2130968585;
        public static final int s_more = 2130968586;
        public static final int post = 2130968587;
        public static final int ok = 2130968588;
        public static final int cancel = 2130968589;
        public static final int tag = 2130968590;
        public static final int warn = 2130968591;
        public static final int blogtype = 2130968592;
        public static final int load = 2130968593;
        public static final int s_about = 2130968594;
        public static final int s_help = 2130968595;
        public static final int s_title_permission = 2130968596;
        public static final int s_title_prompt = 2130968597;
        public static final int s_title_warn = 2130968598;
        public static final int s_info_prompt = 2130968599;
        public static final int s_info_warn = 2130968600;
    }

    public static final class id {
        public static final int text1 = 2131034112;
        public static final int linear_foot = 2131034113;
        public static final int lin_install = 2131034114;
        public static final int lin_appoint = 2131034115;
        public static final int lin_trust = 2131034116;
        public static final int lin_more = 2131034117;
        public static final int activityInfo_img = 2131034118;
        public static final int activityInfo_name = 2131034119;
        public static final int activityInfo_packageName = 2131034120;
        public static final int cb_cancel_trust = 2131034121;
        public static final int lin_bottom = 2131034122;
        public static final int lin_botton_btn = 2131034123;
        public static final int bt_content_top = 2131034124;
        public static final int lv_content = 2131034125;
    }
}
